version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.7.0
    environment:
      TZ: "/usr/share/zoneinfo/Australia/Melbourne"
    steps:
      - checkout
      - run: sudo npm update -g
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  test:
    docker:
      - image: circleci/node:10.7.0
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
      - run: npm test
  deploy:
    docker:
      - image: circleci/node:10.7.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependency-cache-{{ checksum "package.json" }}
      - run: npm run build
      - add_ssh_keys:
          fingerprints:
            - "05:96:54:85:36:aa:08:2f:ab:6c:76:66:e7:19:a9:0b"
      - run: ./deploy.sh

workflows:
  version: 2
  build_test_deploy:
      jobs:
        - build
        - test:
            requires:
              - build
        - deploy:
            requires:
              - test
            filters:
              branches:
                only: master
